biohome/biohome/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.defaults import page_not_found, permission_denied
from django.views.static import serve
from machina.app import board

urlpatterns = [
    url(r'^404/$', page_not_found, kwargs={'exception': Exception("Page not found")}),
    url(r'^403/$', permission_denied, kwargs={'exception': Exception("Permission denied")}),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls')),
    url(r'^', include('dashboard.urls')),
    url(r'^sheets/', include('sheets.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^programs/', include('programs.urls')),
    url(r'^biomes/', include('biomes.urls')),
    url(r'^forum/', include(board.urls)),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

biohome/biomes/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView

from biomes.views import (
    BiomeList,
    BiomeCreate,
    BiomePairing,
    BiomeUpdate,
    BiomeDetail,
    BiomeDelete,

    BiomeModuleList,
    BiomeModuleCreate,
    BiomeModuleUpdate,
    BiomeModuleDetail,
    BiomeModuleDelete,

    BiomeCultureEventView,
)

biome_patterns = [
    url(r'^$', BiomeList.as_view(), name='biome_list'),
    url(r'^add$', BiomeCreate.as_view(), name='biome_create'),
    url(r'^pair$', BiomePairing.as_view(), name='biome_pairing'),
    url(r'^(?P<pk>\d+)?/$', RedirectView.as_view(pattern_name="biome_detail")),
    url(r'^(?P<pk>\d+)/update$', BiomeUpdate.as_view(), name='biome_update'),
    url(r'^(?P<pk>\d+)/details$', BiomeDetail.as_view(), name='biome_detail'),
    url(r'^(?P<pk>\d+)/delete$', BiomeDelete.as_view(), name='biome1_delete'),
]

module_patterns = [
    url(r'^$', BiomeModuleList.as_view(), name='module_list'),
    url(r'^add$', BiomeModuleCreate.as_view(), name='module_create'),
    url(r'^(?P<pk>\d+)?/$', RedirectView.as_view(pattern_name="module_detail")),
    url(r'^(?P<pk>\d+)/update$', BiomeModuleUpdate.as_view(), name='module_update'),
    url(r'^(?P<pk>\d+)/details$', BiomeModuleDetail.as_view(), name='module_detail'),
    url(r'^(?P<pk>\d+)/delete$', BiomeModuleDelete.as_view(), name='module1_delete'),
]

event_patterns = [
    url(r'^culture$', BiomeCultureEventView.as_view(), name='culture_event'),
]

urlpatterns = [
   url(r'^', include(biome_patterns)),
   url(r'^module/', include(module_patterns)),
   url(r'^event/', include(event_patterns)),
]

biohome/users/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView

from .views import (
    Login, Logout, signup, get_csrf_token,
    AccountActivate,
    PasswordChange, PasswordChangeDone,
    PasswordReset, PasswordResetDone,
    PasswordResetConfirm, PasswordResetComplete,
    UserDetail
)
from users.views.profile import UserList

auth_patterns = [
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^signup/$', signup, name='signup'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        AccountActivate.as_view(), name='account_activate'),

    url(r'^account/password/change/$',
        PasswordChange.as_view(), name='password_change'),
    url(r'^account/password/change/done/$',
        PasswordChangeDone.as_view(), name='password_change_done'),

    url(r'^account/password/reset/$',
        PasswordReset.as_view(), name='password_reset'),
    url(r'^account/password/reset/done/$',
        PasswordResetDone.as_view(), name='password_reset_done'),

    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    url(r'^password/reset/done/$',
        PasswordResetComplete.as_view(), name='password_reset_complete')
]

#   Profile patterns :
#       - Users list (/users/)
#       - User details (/users/<pk>/ ou /users/<pk>/details/)
#       - Profile edit (/users/<pk>/edit/)
profile_patterns = [
    url(r'^$', UserList.as_view(), name='users_list'),
    url(r'^(?P<pk>\d+)?/$', RedirectView.as_view(pattern_name='user_details'), name='user_redirect'),
    url(r'^(?P<pk>\d+)?/details/$', UserDetail.as_view(), name='user_details'),
    #url(r'^(?P<pk>\d+)?/edit/$', ProfileUpdate.as_view(), name='user_edit')
]

urlpatterns = [
    url(r'^', include(auth_patterns)),
    url(r'^get-token/$', get_csrf_token, name='get_csrf_token'),
    url(r'^users/', include(profile_patterns)),
]

biohome/biomes/models/biome.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from users.models import User
from programs.models import Program, ProgramCycle

import random
import string

class Biome(models.Model):
    name = models.CharField(
        _('name'),
        max_length=80,
        null=True,
        help_text=_("The biome's name"),
    )

    token = models.CharField(
        _('token'),
        max_length=250,
        null=True,
        blank=True,
        help_text=_("The biome's pairing token"),
    )

    ip = models.GenericIPAddressField(
        _('ip'),
        null=True,
        blank=True,
        help_text=_("The biome's IP"),
    )

    owner = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text=_("The biome's owner"),
    )

    program = models.ForeignKey(
        Program,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text=_("The biome's current program"),
    )

    program_start = models.DateTimeField(
        _('program started on'),
        blank=True,
        null=True,
        help_text=_('The date and time on which the current program was'
                    'started'),
    )

    current_cycle = models.ForeignKey(
        ProgramCycle,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text=_("The current program's cycle"),
    )

    class Meta:
        ordering = ['ip', 'owner']
        verbose_name = _('biome')
        verbose_name_plural = _('biomes')

    def __str__(self):
        return self.name

    def natural_key(self):
        return {
            'name': self.name,
            'id': self.pk,
        }

    def get_modules(self):
        from biomes.models import BiomeModule
        return BiomeModule.objects.filter(biome=self.pk)

    def generate_token(self):
        self.token = ''.join(random.choice(string.ascii_uppercase) for _ in range (6))
        if len(Biome.objects.filter(token=self.token)) > 0:
            self.generate_token()

biohome/biomes/models/module.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from users.models import User
from biomes.models import Biome, BiomeModuleType

class BiomeModule(models.Model):
    type = models.ForeignKey(
        BiomeModuleType,
        null=True,
        on_delete=models.SET_NULL,
        help_text=_("The module's type"),
    )

    biome = models.ForeignKey(
        Biome,
        null=True,
        on_delete=models.SET_NULL,
        help_text=_("The biome this module is attached to"),
    )

    active = models.BooleanField(
        _('is active'),
        default=False,
        help_text=_('Should the module be active'),
    )

    class Meta:
        ordering = ['type', 'active']
        verbose_name = _('biome module')
        verbose_name_plural = _('biome modules')

    def __str__(self):
        if self.type:
            return str(self.type)
        return _('module')

    def natural_key(self):
        ret = {
            'type': self.type.natural_key(),
            'active': self.active,
            'id': self.pk,
        }
        if self.biome:
            ret['biome'] = self.biome.natural_key()
        return ret

biohome/biomes/forms/biome.py
from django import forms

from biomes.models import Biome
from widgets import widgets

class BiomeForm(forms.ModelForm):
    class Meta:
        model = Biome
        fields = [
            'name',
            'ip',
            'program',
            'current_cycle',
        ]

        widgets = {
            'name': widgets.TextInput,
            'ip': widgets.TextInput,
            'program': widgets.Select,
            'current_cycle': widgets.Select,
        }

class BiomePairingForm(forms.ModelForm):
    class Meta:
        model = Biome
        fields = [
            'token',
        ]

        widgets = {
            'token': widgets.TextInput,
        }

biohome/biomes/forms/module.py
from django import forms

from biomes.models import BiomeModule
from widgets import widgets

class BiomeModuleForm(forms.ModelForm):
    class Meta:
        model = BiomeModule
        fields = [
            'type',
            'active',
            'biome',
        ]

        widgets = {
            'type': widgets.widgets.Select,
            'active': widgets.CheckboxInput,
            'biome': widgets.widgets.Select,
        }

biohome/biomes/forms/module_type.py
from django import forms

from biomes.models import BiomeModuleType
from widgets import widgets

class BiomeModuleTypeForm(forms.ModelForm):
    class Meta:
        model = BiomeModuleType
        fields = [
            'name',
            'version',
        ]

        widgets = {
            'name': widgets.TextInput,
            'active': widgets.CheckboxInput,
        }

biohome/biomes/views/biome.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.http import HttpResponseRedirect
from django.forms.utils import ErrorList
from django.utils.translation import ugettext_lazy as _

from biomes.models import Biome, BiomeModule
from biomes.forms import BiomeForm, BiomePairingForm

from biomes.views import (
    GenericBiomeView,
    GenericBiomeListView,
    GenericBiomeCreateView,
    GenericBiomeUpdateView,
    GenericBiomeDetailView,
)

from biomes.models.events import (
    BiomeReadingEvent,
    BiomeReadingEventData,
)

class BiomeView(LoginRequiredMixin):
    model = Biome
    form_class = BiomeForm
    success_url = reverse_lazy('biome_list')

class BiomeList(BiomeView, GenericBiomeListView):

    def get_modules(self, biome):
        modules = BiomeModule.objects.filter(biome=biome.pk)
        modules = [m for m in modules]
        return modules

    def get_context_data(self, **kwargs):
        context = super(GenericBiomeListView, self).get_context_data(**kwargs)
        if 'object_list' in context:
            context['modules'] = []
            for biome in context['object_list']:
                context['modules'].append(len(self.get_modules(biome)))
        return context

class BiomeCreate(BiomeView, GenericBiomeCreateView):
    pass

class BiomePairing(BiomeView, GenericBiomeCreateView):
    template_name_suffix = '_pairing'
    form_class = BiomePairingForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = form.instance
        token = form['token'].value()

        # Invalid token
        if len(token) is not 6:
            if form._errors is None:
                form._errors = {}
            errors = form._errors.setdefault('token', ErrorList())
            errors.append(_('Invalid token, must be a 6 chars len string'))
            return self.form_invalid(form)

        queryset = self.model.objects.filter(token=token)
        # Unknown token
        if len(queryset) is not 1:
            if form._errors is None:
                form._errors = {}
            errors = form._errors.setdefault('token', ErrorList())
            errors.append(_('This token doesn\'t exist'))
            return self.form_invalid(form)

        biome = queryset[0]
        biome.token = None
        biome.owner = request.user
        biome.save()
        return HttpResponseRedirect(self.get_success_url())

class BiomeUpdate(BiomeView, GenericBiomeUpdateView):
    pass

class BiomeDetail(BiomeView, GenericBiomeDetailView):
    def get_readings(self, biome):
        readingqs = BiomeReadingEvent.objects.filter(biome=biome.pk).order_by('-timestamp')[:12]
        readings = dict()
        for reading in readingqs:
            dataqs = BiomeReadingEventData.objects.filter(reading=reading.pk, module__active=True).select_related('module__type')
            for data in dataqs:
                datatype = str(data.module.type.name)
                if datatype not in readings:
                    readings[datatype] = [0, data.avg]
                else:
                    x = int(len(readings[datatype]) / 2)
                    readings[datatype].extend([len(readings[datatype]) / 2, data.avg])
        return readings

    def get_modules(self, biome):
        modules = BiomeModule.objects.filter(biome=biome.pk)
        modules = [m for m in modules]
        return modules

    def get_context_data(self, **kwargs):
        context = super(GenericBiomeDetailView, self).get_context_data(**kwargs)
        if 'object' in context:
            biome = context['object']
            context['readings'] = self.get_readings(biome)
            context['modules'] = self.get_modules(biome)
        return context

class BiomeDelete(BiomeView, GenericBiomeView, DeleteView):
    pass

biohome/biomes/views/genericbiomeviews.py
from django.core import serializers
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView
)

from biomes.serializers import BiomeSerializer

from json_serializer import errors_to_json

import json

class GenericBiomeView:
    def get_template_names(self):
        if self.template_name:
            return self.template_name
        if hasattr(self, 'object_list'):
            opts = self.object_list.model._meta
        else:
            opts = self.model._meta
        return ('%s/%s%s.html' % (opts.model_name, opts.model_name, self.template_name_suffix))

class GenericBiomeListView(GenericBiomeView, ListView):
    def get_queryset(self):
        user = self.request.user
        queryset = self.model.objects.all()
        if user.is_superuser:
            return queryset
        return queryset.filter(owner=user.id)

    def get(self, request):
        if request.META.get('HTTP_ACCEPT') == 'application/json':
            fields = self.form_class._meta.fields
            result = serializers.serialize('json', self.get_queryset(), fields=fields)
            parsed = json.loads(result)
            return JsonResponse(parsed, safe=False)
        return super(ListView, self).get(request)

class GenericBiomeCreateView(GenericBiomeView, CreateView):
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if request.content_type == 'application/json':
            data = json.loads(request.body.decode('utf-8'))
            form = self.form_class(data=data)
        if form.is_valid():
            biome = form.instance
            biome.save()
            if request.META.get('HTTP_ACCEPT') == 'application/json':
                return JsonResponse({
                    'response': 'biome added successfully',
                    'biome_id' : biome.pk
                }, status=200)
            else:
                self.object = biome
                return HttpResponseRedirect(self.get_success_url())
        else:
            if request.META.get('HTTP_ACCEPT') == 'application/json':
                return JsonResponse({
                    'error': errors_to_json(form.errors)
                }, status=400)
            else:
                return self.form_invalid(form)

class GenericBiomeUpdateView(GenericBiomeView, UpdateView):
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST, instance=self.object)
        if request.content_type == 'application/json':
            data = json.loads(request.body.decode('utf-8'))
            form = self.form_class(data=data, instance=self.object)
        if form.is_valid():
            biome = form.instance
            biome.save()
            if request.META.get('HTTP_ACCEPT') == 'application/json':
                return JsonResponse({
                    'response': 'biome updated successfully',
                    'biome_id' : biome.pk
                }, status=200)
            else:
                self.object = biome
                return HttpResponseRedirect(self.get_success_url())
        else:
            if request.META.get('HTTP_ACCEPT') == 'application/json':
                return JsonResponse({
                    'error': form.errors.as_text()
                }, status=400)
            else:
                return self.form_invalid(form)

class GenericBiomeDetailView(GenericBiomeView, DetailView):
    def get(self, request, pk):
        if request.META.get('HTTP_ACCEPT') == 'application/json':
            fields = self.form_class._meta.fields
            result = BiomeSerializer().serialize([self.model.objects.get(pk=pk)], fields=fields, use_natural_foreign_keys=True)
            parsed = json.loads(result)
            return JsonResponse(parsed, safe=False)
        return super(DetailView, self).get(request)

biohome/biomes/templates/biome/biome_confirm_delete.html
{% extends 'base.html' %}

<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>

biohome/biomes/templates/biome/biome_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load string_extras %}

{% block content %}

    <script type="text/javascript" src="/static/js/graphModules.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqPlot/1.0.9/plugins/jqplot.highlighter.js" integrity="sha256-VH+UCHtynUG7uZBAjdTxBMe5VGeGidYnJcOeC1xqyvg=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqPlot/1.0.9/plugins/jqplot.canvasAxisLabelRenderer.js" integrity="sha256-xn5zTvp/lPDVVEkWhlXJXiEURkiJTzeOgtXyzbU1x/s=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqPlot/1.0.9/plugins/jqplot.canvasTextRenderer.js" integrity="sha256-43WkbFuOtOYU+epI3gZ/uikps8DpxVj48VAP1NtAUi4=" crossorigin="anonymous"></script>

    <div class="row justify-content-between align-items-center mb-4">
        <h1 class="display-4 mb-0">{{ object.name }}</h1>
        <div class="d-flex align-items-end text-right">
            <div class="text-right">
                <a href="{% url 'biome_update' object.pk %}">
                    <button id="submit" class="btn btn-biohome">
                        {% trans 'Edit' %}
                        <span class="fa fa-pencil-square-o"></span>
                    </button>
                </a>
                <button type="button" class="btn btn-biohome-wrong" data-toggle="modal" data-target="#modalDeleteBiome">
                    {% trans 'Delete' %}
                    <span class="fa fa-trash-o"></span>
                </button>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalDeleteBiome" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Deleting biome "{{ object.name }}"</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    You're about deleting the biome named <strong>{{ object.name }}</strong>.
                    Are you sure you want to do this ?
                </div>
                <div class="modal-footer">
                    <form action="{% url 'biome1_delete' object.pk %}" method="post">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, thanks</button>
                        <input type="submit" class="btn btn-biohome-wrong" value="{% trans 'Yep, delete it' %}" />
                    </form>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="row justify-content-center mt-4">
        <div class="col">
            <ul class="nav nav-tabs" id="biomeTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="modules-tab" data-toggle="tab" href="#modules" role="tab" aria-controls="modules" aria-selected="true">{% trans 'Modules' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="program-tab" data-toggle="tab" href="#program" role="tab" aria-controls="program" aria-selected="false">{% trans 'Program' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="cycle-tab" data-toggle="tab" href="#cycle" role="tab" aria-controls="cycle" aria-selected="false">{% trans 'Cycle' %}</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="tab-content px-4 mt-4" id="biomeTabContent">
        <div class="tab-pane fade show active" id="modules" role="tabpanel" aria-labelledby="modules-tab">
            <h3 class="mb-3">{% trans 'Modules' %}</h3>
            {% if modules %}
                {% for module in modules %}
                    <form action="{% url 'module_update' module.pk %}" method="post" id="module_{{ module.pk }}_form">
                        <input type="hidden" name="type" value="{{ module.type.pk }}">
                        {% if module.active == True %}
                            <input type="hidden" name="active" value=False>
                        {% else %}
                            <input type="hidden" name="active" value=True>
                        {% endif %}
                        <input type="hidden" name="biome" value="{{ module.biome.pk }}">
                        <input type="hidden" name="next" value="{% url 'biome_detail' object.pk %}">
                    </form>
                {% endfor %}

                <table class="table table-hover table-responsive text-center">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th class="w-25 align-middle">Module name</th>
                            <th class="w-25 align-middle">Module version</th>
                            <th class="w-25 align-middle">Module activity</th>
                            <th class="w-25 align-middle">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for module in modules %}
                            <tr>
                                <td class="align-middle">{{ forloop.counter0 }}</td>
                                <td class="align-middle"><a href="{% url 'module_detail' module.pk %}">{{ module.type.name }}</a></td>
                                <td class="align-middle">{{ module.type.version }}</td>
                                {% if module.active %}
                                    <td class="success align-middle"><span class="badge badge-biohome">{% trans 'Active' %}</span></td>
                                    <td><button class="btn btn-biohome-wrong" type="submit" form="module_{{ module.pk }}_form">{% trans 'Deactivate' %}</button>
                                {% else %}
                                    <td class="danger align-middle"><span class="badge badge-biohome-wrong">{% trans 'Inactive' %}</span></td>
                                    <td><button class="btn btn-biohome" type="submit" form="module_{{ module.pk }}_form">{% trans 'Activate' %}</button>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <em>{% trans 'There is no module in this biome.' %}</em>
            {% endif %}
        </div>
        <div class="tab-pane fade" id="program" role="tabpanel" aria-labelledby="program-tab">
            <h3 class="mb-3">{% trans 'Program currently running' %}</h3>
            <p>
                {% if object.program %}
                    <a href="{% url 'program_detail' object.program.pk %}" class="btn btn-biohome">
                        {{ object.program.name }}
                    </a>
                {% else %}
                    <span class="badge badge-secondary">{% trans 'None' %}</span>
                {% endif %}
            </p>
        </div>
        <div class="tab-pane fade" id="cycle" role="tabpanel" aria-labelledby="cycle-tab">
            <h3 class="mb-3">{% trans 'Cycle currently running' %}</h3>
            <p>
                {% if object.current_cycle %}
                    <a href="{% url 'cycle_detail' object.current_cycle.pk %}" class="btn btn-biohome">
                        {{ object.current_cycle }}
                    </a>
                {% else %}
                    <span class="badge badge-secondary">{% trans 'None' %}</span>
                {% endif %}
            </p>
        </div>
    </div>

    <hr />

	{% for key, val in readings.items %}
        <div class="row">
            <div class="col-12">
                <h3 class="display-5 text-center">{{ key }}</h3>
                <div name="readings" data-name="{{ key|replace_spaces }}" data-values="{{ val }}" id="{{ key|replace_spaces }}"></div>
                {% if not forloop.last %}
                    <hr />
                {% endif %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

biohome/biomes/templates/biome/biome_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Biohome" %} / {% trans "Biome" %} / {% trans "Form" %}{% endblock %}

{% block content %}

    <body>
        <div class="container">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <br/>
                <div class="text-center">
                    <input class="btn btn-default" align="center" type="submit" value="{% trans 'Save' %}">
                </div>
            </form>
        </div>
    </body>

{% endblock %}

biohome/biomes/templates/biome/biome_pairing.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <div class="row justify-content-center" style="margin-top: 10%; margin-bottom: 4%">
        <div class="col-12">
            <h1 class="text-center">
                <span class="fa fa-cogs"></span>
                {% trans "Let's pair a biome !" %}
            </h1>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col">
            <form action="" method="post" class="form-group" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row justify-content-center">
                    <div class="col-6">
                        <input type="text" name="token" id="id_token" class="form-control" placeholder="{% trans "Enter the biome token here !" %}">
                    </div>

                    <div class="col-auto">
                        <button id="submit" class="btn btn-biohome">
                            Pair
                            <span class="fa fa-plug"></span>
                        </button>
                    </div>
                </div>
            </form>

            {% if form.errors %}
                <div class="row justify-content-center">
                    <div class="col-6 text-center">
                        <h1 class="display-5 mt-5">
                            Bad token
                            <span class="fa fa-ticket" style="color: #b51a14"></span>
                        </h1>
                    </div>
                </div>

                <div class="row justify-content-center mt-3">
                    <div class="col-6 text-center alert alert-danger" role="alert">
                        <p class="mb-0 text-dark">
                            It may be incorrect or has already been used.<br/>
                            Please, <a href="{% url 'biome_pairing' %}" class="alert-link">try again</a> !
                        </p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{#    <body>#}
{#        <div class="container" style="width: 400px">#}
{#            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}#}
{#                {{ form.as_p }}#}
{#                <br/>#}
{#                <div class="text-center">#}
{#                    <input class="btn btn-default" align="center" type="submit" value="{% trans 'Save' %}">#}
{#                </div>#}
{#            </form>#}
{#        </div>#}
{#    </body>#}

{% endblock %}